### ISSUE TITLE
Register on Packagist

### ISSUE THREAD

**Issue by Soullivaneuh** [StyleCI/SDK#1]
I'm starting to work with your new project as you suggested on https://github.com/Soullivaneuh/styleci-fixers/issues/1 but the package is not registered on Packagist yet: https://packagist.org/search/?q=styleci%2Fsdk

Could you please solve that?

Thanks.

**Comment by GrahamCampbell** [comment]
Oh, sorry!

**Comment by GrahamCampbell** [comment]
Registered it with packagist now. Let me know if it's working now. ;)
