### ISSUE TITLE
Provide an interface

### ISSUE THREAD

**Issue by theofidry** [StyleCI/SDK#2]
Having only a class `Client` without an interface force the user to use inheritance if they wish to override the client where decorating could be preferable.

**Comment by GrahamCampbell** [comment]
We'll make architecture adjustments in 2.x when this library gets larger. For now, I see little point.

**Comment by GrahamCampbell** [comment]
It should also be noted that adding an interface makes it impossible for us to add anything to the library though without a major version bump each time.
