### ISSUE TITLE
Wrong symfony fixer

### ISSUE THREAD

**Issue by core23** [StyleCI/SDK#5]
According to the [php-cs-fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer) docs, the `simplified_null_return` fixer is no valid symfony fixer and is risky. So why is it [listed](https://styleci.readme.io/docs/presets#section-symfony) as a symfony fixer

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. This does look like an error. Do note that there does not exist a bijection between StyleCI and PHP-CS-Fixer, however, at this point, we are now closer than ever before in terms of behaviour, but we're wider apart in terms of configuration than ever before.

Note that this bug tracker is for bugs in the SDK, and this ticket is unrelated.

**Comment by core23** [comment]
Thanks for your fast answer 👍 

I was looking for a bug tracker or a slack channel but didn't find any. Is there any other communication channel besides email?

**Comment by GrahamCampbell** [comment]
Our support email address is the best way to get in touch with us. :)

**Comment by GrahamCampbell** [comment]
@core23 This fixer has now been removed from our symfony preset. Thanks for the report.

**Comment by core23** [comment]
Thanks :)
