### ISSUE TITLE
Docker Hub can't render README.md badge

### ISSUE THREAD

**Issue by francescobianco** [StyleCI/SDK#8]
Hi StyleCI

my projects from GitHub when goes to Docker Hub lose the Badge images, take a look on below
![Screenshot from 2020-05-19 15-50-00](https://user-images.githubusercontent.com/472171/82416432-53276600-9a7a-11ea-99c2-15937f00533a.png)

Visit this as examples
- https://github.com/javanile/vtiger (GITHUB works)
- https://hub.docker.com/r/javanile/vtiger

**Comment by GrahamCampbell** [comment]
This repo is only for reporting issues with the SDK codebase.
